stages:
  train_file_new:
    cmd: python train_file_new.py --img 640 --batch 16 --epochs 10 --data VisDrone.yaml
      --weights yolov5n.pt
    metrics:
    - new_timing_info.json
  detect:
    cmd: python detect_new.py --weights  yolov5n.onnx --source /content/drive/MyDrive/project_lab/images
    metrics:
    - detect_info.json
